<?php
/**
 * Page layouts (Option B): which theme sections a page shows, in which order.
 *
 * The COPY of these pages (H1, intro, "how to choose" cards, link lists, FAQs) is edited in
 * WordPress with built-in blocks. This file only decides the layout around it:
 *
 *   'hero'     eyebrow, buttons and product visuals for the page header
 *              (showProducts: WooCommerce "Featured" products; categories: featured/newest from
 *              those product categories). The H1 and intro come from the page's first
 *              Heading (H1) and Paragraph blocks.
 *   'sections' in order. type "content" = the next block of the page content
 *              (e.g. a Group styled "MedHub: FAQ"); any other type is a dynamic section from
 *              template-parts/sections/ filled from WooCommerce/WordPress.
 *
 * Keys: "home" for the front page, otherwise the page slug (invisible characters ignored).
 * Pages without an entry use the default layout (hero + content + closing call to action).
 *
 * First generated by tooling/content/build.mjs; maintained by hand from here on.
 *
 * @package MedHub
 */

defined( 'ABSPATH' ) || exit;

return array(
	'home' => array(
		'hero' => array(
			'eyebrow' => 'Medical equipment · Deira, Dubai',
			'primaryLabel' => 'Explore Medical Equipment',
			'primaryUrl' => '/shop/',
			'secondaryLabel' => 'Medical Equipment Rental',
			'secondaryUrl' => '/product-category/medical-equipment-rental/',
			'showProducts' => true,
		),
		'sections' => array(
			array( 'type' => 'trust' ),
			array( 'type' => 'marquee', 'source' => 'departments' ),
			array(
				'type' => 'explorer',
				'eyebrow' => 'Shop by need',
				'heading' => 'Find the right equipment, *faster.*',
				'lead' => 'Eight departments, from oxygen and sleep therapy to hospital beds and everyday medical supplies.',
			),
			array( 'type' => 'showcase', 'eyebrow' => 'In the catalogue', 'heading' => 'Featured *equipment*', 'linkLabel' => 'Shop all equipment' ),
			array( 'type' => 'content' ),
			array(
				'type' => 'brands',
				'eyebrow' => 'Brands',
				'heading' => 'Brands in *our range*',
				'lead' => 'Every brand below has products in the catalogue today.',
			),
			array(
				'type' => 'rental',
				'eyebrow' => 'Medical equipment rental',
				'heading' => 'Need it for weeks, *not years?*',
				'lead' => 'Rent oxygen concentrators, CPAP machines, hospital beds, suction units, feeding pumps and patient monitors by the month.',
				'ctaLabel' => 'See all rental equipment',
			),
			array(
				'type' => 'switcher',
				'eyebrow' => 'Sleep & respiratory care',
				'heading' => 'Compare by *equipment type.*',
				'lead' => 'Choose a category to see what it covers and what is available now.',
			),
			array( 'type' => 'service', 'eyebrow' => 'Dubai delivery & support', 'heading' => 'From our shelves *to your door.*' ),
			array(
				'type' => 'posts',
				'eyebrow' => 'Guides',
				'heading' => 'Know before *you buy.*',
				'lead' => 'Plain-language guides to oxygen therapy, sleep apnea equipment and patient care.',
			),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Not sure what fits?',
				'heading' => 'Talk to MedHub *before* you buy.',
				'text' => 'Tell us what you need and we will help you compare options, whether you are buying or renting.',
				'primaryLabel' => 'Shop Medical Equipment',
				'primaryUrl' => '/shop/',
				'secondaryLabel' => 'Rent Equipment',
				'secondaryUrl' => '/product-category/medical-equipment-rental/',
			),
		),
	),
	'medical-equipment' => array(
		'hero' => array(
			'eyebrow' => 'About MedHub',
			'primaryLabel' => 'Explore the catalogue',
			'primaryUrl' => '/shop/',
			'secondaryLabel' => 'Contact MedHub',
			'secondaryUrl' => '/contact-us-medhub/',
		),
		'sections' => array(
			array( 'type' => 'trust' ),
			array( 'type' => 'content' ),
			array( 'type' => 'explorer', 'eyebrow' => 'What we supply', 'heading' => 'Eight departments, *one supplier.*' ),
			array( 'type' => 'brands', 'eyebrow' => 'Brands', 'heading' => 'Brands in *our range*', 'limit' => 12 ),
			array( 'type' => 'service', 'eyebrow' => 'Ordering', 'heading' => 'Ordering and *delivery*' ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Get in touch',
				'heading' => 'Talk to MedHub *before* you buy.',
				'text' => 'Tell us what you need and we will help you compare options, whether you are buying or renting.',
				'primaryLabel' => 'Shop Medical Equipment',
				'primaryUrl' => '/shop/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'cpap-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Sleep care',
			'primaryLabel' => 'Shop CPAP machines',
			'primaryUrl' => '/product-category/auto-cpap-machine/',
			'secondaryLabel' => 'Rent a CPAP',
			'secondaryUrl' => '/product-category/medical-equipment-rental/',
			'categories' => 'auto-cpap-machine,cpap,travel-cpap-machine',
		),
		'sections' => array(
			array( 'type' => 'content' ),
			array(
				'type' => 'products',
				'eyebrow' => 'Available now',
				'heading' => 'CPAP machines',
				'categories' => 'auto-cpap-machine,cpap,travel-cpap-machine',
				'limit' => 4,
				'linkLabel' => 'See all auto CPAP',
			),
			array( 'type' => 'content' ),
			array( 'type' => 'service', 'eyebrow' => 'Buying from MedHub', 'heading' => 'Delivery and *support*' ),
			array( 'type' => 'posts', 'eyebrow' => 'Guides', 'heading' => 'CPAP *guides*', 'category' => 'cpap-and-bipap', 'count' => 3 ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Not sure which CPAP?',
				'heading' => 'Compare CPAP options *with us.*',
				'text' => 'Tell us about your prescription and how you sleep, and we will suggest machines and masks that fit.',
				'primaryLabel' => 'Shop CPAP machines',
				'primaryUrl' => '/product-category/auto-cpap-machine/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'bipap-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Sleep & respiratory care',
			'primaryLabel' => 'Shop BiPAP machines',
			'primaryUrl' => '/product-category/bipap/',
			'secondaryLabel' => 'Auto BiPAP',
			'secondaryUrl' => '/product-category/auto-bipap-machine/',
			'categories' => 'bipap,auto-bipap-machine',
		),
		'sections' => array(
			array(
				'type' => 'products',
				'eyebrow' => 'Available now',
				'heading' => 'BiPAP machines',
				'categories' => 'bipap,auto-bipap-machine',
				'limit' => 4,
				'linkLabel' => 'See all BiPAP',
			),
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array( 'type' => 'posts', 'eyebrow' => 'Guides', 'heading' => 'BiPAP *guides*', 'category' => 'cpap-and-bipap', 'count' => 3 ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Questions about BiPAP?',
				'heading' => 'Choose the right machine *with us.*',
				'text' => 'Share your prescription and we will help you compare BiPAP models and masks.',
				'primaryLabel' => 'Shop BiPAP machines',
				'primaryUrl' => '/product-category/bipap/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'oxygen-concentrator-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Oxygen therapy',
			'primaryLabel' => 'Shop oxygen concentrators',
			'primaryUrl' => '/product-category/buy-oxygen-concentrator/',
			'secondaryLabel' => 'Rent monthly',
			'secondaryUrl' => '/product-category/medical-equipment-rental/',
			'categories' => 'buy-oxygen-concentrator',
		),
		'sections' => array(
			array(
				'type' => 'products',
				'eyebrow' => 'Home concentrators',
				'heading' => 'Available *now*',
				'categories' => 'buy-oxygen-concentrator',
				'limit' => 4,
				'linkLabel' => 'See all home concentrators',
			),
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array( 'type' => 'posts', 'eyebrow' => 'Guides', 'heading' => 'Oxygen *guides*', 'category' => 'oxygen-machine', 'count' => 3 ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Need oxygen at home?',
				'heading' => 'Find the right concentrator *with us.*',
				'text' => 'Share the flow rate you need and we will suggest home, portable or rental options.',
				'primaryLabel' => 'Shop concentrators',
				'primaryUrl' => '/product-category/buy-oxygen-concentrator/',
				'secondaryLabel' => 'Rent equipment',
				'secondaryUrl' => '/product-category/medical-equipment-rental/',
			),
		),
	),
	'portable-oxygen-machine-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Portable oxygen',
			'primaryLabel' => 'Shop portable concentrators',
			'primaryUrl' => '/product-category/portable-oxygen-concentrator/',
			'secondaryLabel' => 'Rent monthly',
			'secondaryUrl' => '/product-category/medical-equipment-rental/',
			'categories' => 'portable-oxygen-concentrator',
		),
		'sections' => array(
			array(
				'type' => 'products',
				'eyebrow' => 'Portable concentrators',
				'heading' => 'Available *now*',
				'categories' => 'portable-oxygen-concentrator',
				'limit' => 4,
				'linkLabel' => 'See all portable concentrators',
			),
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array( 'type' => 'posts', 'eyebrow' => 'Guides', 'heading' => 'Portable oxygen *guides*', 'category' => 'oxygen-machine', 'count' => 3 ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Planning to travel?',
				'heading' => 'Choose a portable unit *with us.*',
				'text' => 'Tell us your flow setting and how long you need between charges, and we will suggest models.',
				'primaryLabel' => 'Shop portable concentrators',
				'primaryUrl' => '/product-category/portable-oxygen-concentrator/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'oxygen-machine-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Oxygen therapy',
			'primaryLabel' => 'Explore oxygen equipment',
			'primaryUrl' => '/product-category/oxygen-concentrator/',
			'secondaryLabel' => 'Rent monthly',
			'secondaryUrl' => '/product-category/medical-equipment-rental/',
			'categories' => 'buy-oxygen-concentrator,portable-oxygen-concentrator',
		),
		'sections' => array(
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array(
				'type' => 'products',
				'eyebrow' => 'Popular now',
				'heading' => 'Oxygen *equipment*',
				'categories' => 'oxygen-concentrator',
				'limit' => 4,
				'linkLabel' => 'See all oxygen therapy',
			),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Still deciding?',
				'heading' => 'Talk it through *with us.*',
				'text' => 'Tell us how and where you use oxygen, and we will suggest the equipment that fits.',
				'primaryLabel' => 'Explore oxygen equipment',
				'primaryUrl' => '/product-category/oxygen-concentrator/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'sleep-apnea-machine-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Sleep care',
			'primaryLabel' => 'Shop CPAP machines',
			'primaryUrl' => '/product-category/auto-cpap-machine/',
			'secondaryLabel' => 'Shop BiPAP machines',
			'secondaryUrl' => '/product-category/bipap/',
			'categories' => 'auto-cpap-machine,cpap,auto-bipap-machine',
		),
		'sections' => array(
			array(
				'type' => 'switcher',
				'eyebrow' => 'Compare',
				'heading' => 'Sleep apnea machines *by type*',
				'categories' => 'auto-cpap-machine,cpap,travel-cpap-machine,bipap,auto-bipap-machine,buy-cpap-bipap-masks',
			),
			array( 'type' => 'content' ),
			array( 'type' => 'posts', 'eyebrow' => 'Guides', 'heading' => 'Sleep apnea *guides*', 'category' => 'cpap-and-bipap', 'count' => 3 ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Need help choosing?',
				'heading' => 'Talk to MedHub *before* you buy.',
				'text' => 'Bring your prescription and we will help you compare machines and masks.',
				'primaryLabel' => 'Shop sleep care',
				'primaryUrl' => '/product-category/auto-cpap-machine/',
				'secondaryLabel' => 'Contact MedHub',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'devilbiss-service-centre-in-dubai' => array(
		'hero' => array(
			'eyebrow' => 'Service',
			'primaryLabel' => 'Request a service',
			'primaryUrl' => '/contact-us-medhub/?product=DeVilbiss%20service',
			'secondaryLabel' => 'Shop DeVilbiss equipment',
			'secondaryUrl' => '/product-category/oxygen-concentrator/',
			'categories' => 'buy-oxygen-concentrator,suction-machine',
		),
		'sections' => array(
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array( 'type' => 'content' ),
			array(
				'type' => 'cta',
				'eyebrow' => 'Equipment not working?',
				'heading' => 'Book a DeVilbiss *service.*',
				'text' => 'Tell us the model and the problem, and the team will advise on the next step.',
				'primaryLabel' => 'Request a service',
				'primaryUrl' => '/contact-us-medhub/?product=DeVilbiss%20service',
				'secondaryLabel' => 'Visit & contact',
				'secondaryUrl' => '/contact-us-medhub/',
			),
		),
	),
	'contact-us-medhub' => array(
		'hero' => array( 'eyebrow' => 'Contact' ),
		'sections' => array(
			array(
				'type' => 'contact',
				'heading' => 'Reach *the team*',
				'lead' => 'For quotes, include the equipment name and whether you want to buy or rent.',
				'formHeading' => 'Send an enquiry',
				'formLead' => 'We will reply using the details you provide.',
			),
			array( 'type' => 'content' ),
		),
	),
);
